name: q2-docker-image

services:
  common:
    build:
      context: ./
    platform: linux/amd64
    privileged: true
    network_mode: host
    command: /bin/bash
    tty: true
    stdin_open: true
    volumes:
      - ./pkg_1:/home/isi_user/ws_ros/src/pkg_1
      - ./pkg_2:/home/isi_user/ws_ros/src/pkg_2
      - ./pkg_3:/home/isi_user/ws_ros/src/pkg_3
      - ./q2_interfaces:/home/isi_user/ws_ros/src/q2_interfaces
  
  cpu_terminal:
    extends:
      service: common
  
  cpu:
    extends:
      service: cpu_terminal
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
    volumes:    
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XAUTHORITY:/home/isi_user/.Xauthority

  gpu:
    extends:
      service: cpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
